# 1.5.2 生成numpy数组

使用np.array()方法生成数组

In [2]:
import numpy as np

x = np.array([1, 2, 3])
print(x)
type(x)

[1 2 3]


numpy.ndarray

# 1.5.3 Numpy的算术运算


In [8]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
z = np.array([2.0, 4.0, 6.0, 8.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x/2.0)
print(x-z)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

# 1.5.4 Numpy的N维数组

In [11]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


# 1.5.5 广播

In [3]:
# 下面通过这个运算来看一个广播的例子
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A*B



array([[10, 40],
       [30, 80]])

In [7]:
C = 10
D = np.array([[10, 20], [30, 40], [50, 60]])
print(C * D)


[[100 200]
 [300 400]
 [500 600]]


# 1-5-6 访问元素

元素的访问从0开始，对各个元素的访问可按照如下方式进行。


In [20]:
x = np.array([[51, 52], [23, 4], [5, 6]])
print(x)
print(x.shape)
print(x[0])
print(x[0][1])

[[51 52]
 [23  4]
 [ 5  6]]
(3, 2)
[51 52]
52


In [13]:
# 也可以使用for语句来访问各个元素

for row in x:
    print(row)

[1 2]
[3 4]
[5 6]


In [18]:
# 除了前面介绍的索引外，numpy还可以使用数组访问各个元素
x = x.flatten() # 将x转换为一维数组
print(x)
print(x[np.array([0, 2, 4])]) # 获取索引为0、2、4的元素

[1 2 3 4 5 6]
[1 3 5]


In [24]:
# 利用这个标记法，可以获取满足一定条件的元素，例如，要从x中抽出大于15的元素，可以写成下面的形式
print(x > 15)
x[x>15]

[[ True  True]
 [ True False]
 [False False]]


array([51, 52, 23])